spring:
  application:
    name: trading-service
  threads:
    virtual:
      enabled: true

server:
  port: 8302
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
